services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $projectDir: '%kernel.project_dir%'

  DanielGausi\CalendarEditorBundle\:
    resource: ../src/*

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ setFramework, [ '@contao.framework' ] ]

  caledit.service.auth:
      class: DanielGausi\CalendarEditorBundle\Services\CheckAuthService
      public: true