services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      $projectDir: '%kernel.project_dir%'

  DanielGausi\CalendarEditorBundle:
    resource: ../src/*

  _instanceof:
    Contao\CoreBundle\Framework\FrameworkAwareInterface:
      calls:
        - [ setFramework, [ '@contao.framework' ] ]

  Symfony\Component\DependencyInjection\ContainerAwareInterface:
      calls:
        - [ setContainer, [ '@service_container' ] ]

  caledit.service.auth:
      class: DanielGausi\CalendarEditorBundle\Services\CheckAuthService
      public: true