services:
  _defaults:
    autoconfigure: true
    autowire: true
    bind:
      projectDir: '%kernel.project_dir%'

  caledit.service.auth:
      class: DanielGausi\CalendarEditorBundle\Services\CheckAuthService
      public: true