services:
  _defaults:
    autoconfigure: true
    autowire: true

  calendar_eventeditor:
    class: DanielGausi\CalendarEditorBundle\EventListener\DataContainer\CalendarEventsEditor
    public: true

  caledit.service.auth:
      class: DanielGausi\CalendarEditorBundle\Services\CheckAuthService
      public: true